apiDir: "../captcha-rest-api/src/main/java"
apiPackagePath: "com.liferay.captcha.rest"
application:
    baseURI: "/captcha-rest"
    className: "CaptchaRestApplication"
    name: "CaptchaRest"
author: "Loc Pham"
clientDir: "../captcha-rest-client/src/main/java"
testDir: "../captcha-rest-test/src/testIntegration/java"